language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0
install:
  - pip install coveralls coverage
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: coverage run --source=simple_contact runtests.py
after_script:
  - coveralls
