language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.5.2
install:
  - pip install coveralls coverage
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: coverage run --source=simple_contact setup.py test
after_script:
  - coveralls
